// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJgEndEzlROF-lUN4nYT-KV8CNgDn7Yos',
    appId: '1:52241281718:web:7e1bcdfb72f41a7558ec17',
    messagingSenderId: '52241281718',
    projectId: 'lifelink-59c44',
    authDomain: 'lifelink-59c44.firebaseapp.com',
    storageBucket: 'lifelink-59c44.firebasestorage.app',
    measurementId: 'G-1H5KVP6Z0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7WAdUlHWeOJlCLtCNBQKUOHBrwxHapas',
    appId: '1:52241281718:android:489facab94d374ff58ec17',
    messagingSenderId: '52241281718',
    projectId: 'lifelink-59c44',
    storageBucket: 'lifelink-59c44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjQ4AfYU8n1uIsV1aNlkbVeeEH1i1p4WA',
    appId: '1:52241281718:ios:b345f536bf8e041458ec17',
    messagingSenderId: '52241281718',
    projectId: 'lifelink-59c44',
    storageBucket: 'lifelink-59c44.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjQ4AfYU8n1uIsV1aNlkbVeeEH1i1p4WA',
    appId: '1:52241281718:ios:b345f536bf8e041458ec17',
    messagingSenderId: '52241281718',
    projectId: 'lifelink-59c44',
    storageBucket: 'lifelink-59c44.firebasestorage.app',
    iosBundleId: 'com.example.lifelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJgEndEzlROF-lUN4nYT-KV8CNgDn7Yos',
    appId: '1:52241281718:web:cc5ac8d7454ac66358ec17',
    messagingSenderId: '52241281718',
    projectId: 'lifelink-59c44',
    authDomain: 'lifelink-59c44.firebaseapp.com',
    storageBucket: 'lifelink-59c44.firebasestorage.app',
    measurementId: 'G-RCZZTQR5E3',
  );
}
